# render.yaml
services:
  - type: web
    name: cine-delices-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: http://localhost:3001
    healthCheckPath: /
    plan: free
    branch: dev
    
  - type: web
    name: cine-delices-backend
    env: node
    buildCommand: npm install && npx prisma generate
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: cine-delices-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /api/health
    plan: free
    branch: dev

databases:
  - name: cine-delices-db
    plan: free
    ipAllowList: []