services:
  - type: web
    name: backend
    env: docker
    plan: free
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cine-db
          property: connectionString
      - key: JWT_SECRET
        synchronize: false
      - key: TMDB_API_KEY
        synchronize: false

  - type: web
    name: frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    rootDir: front
    envVars:
      - key: VITE_API_URL
        value: https://backend-XXXX.onrender.com/api  # À mettre à jour après déploiement
      - key: VITE_TMDB_API_KEY
        synchronize: false
      - key: VITE_OMDB_API_KEY
        synchronize: false

databases:
  - name: cine-db
    plan: free
