services:
  - type: web
    name: backend
    env: docker
    plan: free
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - fromGroup: CinéDélice-Prod-envVars


  - type: web
    name: frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    rootDir: front
    envVars:
      - fromGroup: CinéDélice-Prod-envVars

databases:
  - name: cine-db
    plan: free
