services:
  - type: static
    name: client
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_TMDB_API_KEY
        value: 1923f2b998e0a232766db7ede4e6c1b9
      - key: VITE_OMDB_API_KEY
        value: 24f1bf71
      - key: VITE_API_BASE_URL
        value: https://backend.onrender.com/api